# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c86194dd15e747758c36fdbe89fcbffe8129d8a661469d84f5295965deede17f677e12ebc4cc5c4a9259a4da2f397811c4ef1c8556d4b43537f0095a950559d

test:
  secret_key_base: c64599738731c7cde380b1bb7cd6de8557cbdf91f565c5046df13ea6f642d9db93458691175f9d8d04704e701f83a50b12f672b16a4734dd1292cfae6bf7215f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
